export const CommonConst = {
  BRAND_NAME: "To Doooo",
  MY_PROFILE: "My Profile",
  ABOUT: "About",
  LOGOUT: "Log Out",
  ADD_TASK: "Add Task",
  TASK_LIST: "Task List",
  ADD_TO_DO: "Add ToDo",
  VERSION: "Version",
  TASKS: "Tasks",
  TO_DOS: "Things To Do",
  DELETE_TASK: "Delete Task",
  ARE_YOU_SURE: "Are you sure you want to delete the task ?",
  YES: "Yes",
  NO: "No",
  LOGIN: "Login",
  USER: "User Name",
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot Password ?",
};
