export const CommonConst = {
  BRAND_NAME: "To Doooo",
  MY_PROFILE: "My Profile",
  ABOUT: "About",
  LOGOUT: "Log Out",
  ADD_TASK: "Add Task",
  TASK_LIST: "Task List",
  ADD_TO_DO: "Add ToDo",
  VERSION: "Version",
  TASKS: "Tasks",
  ALL_TASKS: "All Tasks",
  TO_DOS: "Things To Do",
  DELETE_TASK: "Delete Task",
  ARE_YOU_SURE: "Are you sure you want to delete the task ?",
  YES: "Yes",
  NO: "No",
  LOGIN: "Login",
  USER: "User Name",
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot Password ?",
  CREATE_EVENT: "Create Event",
  EVENT_TYPE: "Event Type",
  ANNIVERSARY: "Anniversary",
  METTING: "Metting",
  BIRTHDAY: "Birthday",
  EVENT: "Event",
  EVENT_NAME: "Event Name",
  DATE: "Date",
  TIME: "Time",
  PRIORITY: "Priority",
  ALERM: "Alerm",
  SUBMIT: "Submit",
};
